app/blueprints/user/routes.py
from flask import Blueprint, request, jsonify, render_template
import logging
from logging.handlers import TimedRotatingFileHandler
import datetime
import os

from app.process import courses
log = logging.getLogger(__name__)
# enable logging routines
# write log to a file with specified filename (provided via environmental variable)
# set needed level and optionally disable logging completely

DEBUGLEVEL = os.getenv('DEBUG_LEVEL','DEBUG')
LOGFILE = os.getenv('DB_LOGFILE_NAME', 'logs/log-courses-app-state.log')
log.disabled = os.getenv('LOG_ON', "True") == "False"

log.setLevel(getattr(logging, DEBUGLEVEL))
handler = TimedRotatingFileHandler(filename=f'{LOGFILE}', encoding='utf-8', when='m', interval=10, backupCount=1)
formatter = logging.Formatter('[%(asctime)s]::[%(levelname)s]::[%(name)s]::%(message)s', '%D # %H:%M:%S')
handler.setFormatter(formatter)
log.addHandler(handler)

log.info(msg=f'LOG STARTED: [{datetime.datetime.now(tz=None)}]')

user_bp = Blueprint(
    'user_bp',
    __name__,
    template_folder='templates/',
    static_folder='static/')

@user_bp.route('/request/services', methods=['POST'])
def post_request_services():
    selected_lang = request.values.get('language_selection')
    selected_lang = 'All languages' if (selected_lang == '') else selected_lang
    
    results = courses.GLOBAL_COURSE_CONTROLLER.get_services_for_language(selected_lang)
    log.debug(msg=f'Controller response: {results}')
    
    if results[0]: return render_template(
        'services_results.j2',
        has_options=True,
        language=selected_lang,
        options=results[1])

    log.debug(msg=f'Did not render bc results are empty!')
    return render_template('services_results.j2', empty=True, language=selected_lang)

@user_bp.route('/request/services', methods=['GET'])
def get_request_services():
    return render_template('services_selection.html')

@user_bp.route('/request/orders', methods=['POST'])
def post_request_orders():
    selected_threshold = request.values.get('threshold')
    results = courses.GLOBAL_COURSE_CONTROLLER.get_orders_for_threshold(selected_threshold)
    log.debug(msg=f'Controller response: {results}')

    if results[0]: return render_template(
        'order_results.j2',
        has_options=True,
        threshold=selected_threshold,
        options=results[1]
    )

    log.debug(msg=f'Did not render bc results are empty!')
    return render_template('services_results.j2', empty=True, threshold=selected_threshold)


@user_bp.route('/request/orders', methods=['GET'])
def get_request_orders():
    return render_template('order_selection.html')

app/blueprints/user/templates/courses_results.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1"> 
        <title>Language courses</title>
        <link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='img/icon.png') }}">
        <link href="{{ url_for('user_bp.static', filename='css/home.css') }}" rel="stylesheet">
        <link href="{{ url_for('user_bp.static', filename='css/table.css') }}" rel="stylesheet">
    </head>
    <body>
        <div class="fetched">
            {% block results %}
            {% endblock %}
        </div>
        <div class="fetched">
            {% block options %}
            {% endblock %}
        </div>
        <div>
            <p>Click <a href="{{ url_for('get_courses_menu') }}">here</a> to go to main menu</p>
        </div>
    </body>
</html>

app/blueprints/user/templates/order_selection.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1">
    <title>Search orders</title>
    <link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='img/icon.png') }}">
    <link href="{{ url_for('user_bp.static', filename='css/home.css') }}" rel="stylesheet">
</head>

<body>
    <div class="section-element">
        <div class="flex-container">
            <aside class="item" id="search-courses">
                <form action="{{ url_for('user_bp.post_request_orders') }}" method="post">
                    <input type="number" name="threshold" placeholder="Filter by price" min="0" max="10000">
                    <input type="submit" placeholder="Search">
                </form>
            </aside>
            <aside class="item bio">
                Filter orders by total price of selected services
            </aside>
        </div>
    </div>
</body>

</html>

app/blueprints/user/templates/services_selection.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1">
    <title>Search services</title>
    <link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='img/icon.png') }}">
    <link href="{{ url_for('user_bp.static', filename='css/home.css') }}" rel="stylesheet">
</head>

<body>
    <div class="section-element">
        <div class="flex-container">
            <aside class="item" id="search-courses">
                <form action="{{ url_for('user_bp.post_request_services') }}" method="post">
                    <input type="text" name="language_selection" placeholder="Write language here">
                    <input type="submit" placeholder="Search">
                </form>
            </aside>
            <aside class="item bio">
                Write language you wish to master!
            </aside>
        </div>
    </div>
</body>

</html>