view/patients/routes.py
from json import loads, dumps
from json.decoder import JSONDecodeError

from flask import (
    Blueprint,
    request,
    render_template,
    redirect,
    url_for,
)

from app import make_logger
from app.policies import requires_login, requires_permission
from controller.patients import PatientController
from controller.hospital import HospitalController

patients_view = make_logger(__name__, 'logs/patients.log')

patients_bp = Blueprint(
    'patients_bp',
    __name__,
    template_folder='templates/',
    static_folder='static/')

@patients_bp.route('menu', methods=['GET'])
@requires_login
@requires_permission
def menu():
    patients_view.info(msg=f'Renders patients menu page')
    return render_template('patient_menu.j2')


@patients_bp.route('/add', methods=['POST', 'GET'])
@requires_login
@requires_permission
def add_new_patient():
    patients_view.info(msg=f'Renders page for new patient record creation')

    if request.method == 'GET':
        return render_template('patient_create.j2')

    attributes = ('first_name', 'passport', 'second_name', 'date_birth', 'city', 'initial_diagnosis')
    new_patient_data = { attribute: request.values.get(attribute) for attribute in attributes }

    status = PatientController().create_patient_record(new_patient_data)
    return render_template('patient_create.j2', status=True, success=status)


@patients_bp.route('/discharge', methods=['POST', 'GET'])
@requires_login
@requires_permission
def list_dischargable():
    patients_view.info(msg=f'Renders page for patient discharging')

    if request.method == 'GET':
        with_diag = PatientController().fetch_dischargable_patients()
        return render_template('patient_discharge.j2', with_diag=with_diag)

    to_remove_id = request.values.get('to_remove_id')
    attending_doc_id = request.values.get('attending_doctor')
    chamber_id = request.values.get('occupied_chamber')

    PatientController().discharge_patient(to_remove_id, attending_doc_id, chamber_id)
    with_diag = PatientController().fetch_dischargable_patients()

    return render_template('patient_discharge.j2', show_alert=True, with_diag=with_diag)


@patients_bp.route('/list', methods=['POST', 'GET'])
@requires_login
@requires_permission
def list_patients():
    patients_view.info(msg=f'Renders patient list')

    patients = PatientController().fetch_unassigned()

    if patients is None:
        patients_view.warning(msg=f'Renders empty page bc fetched data is empty')
        return render_template('hospital_empty.j2')

    if request.method == 'GET':
        
        if 'assign_response' not in request.values:
                return render_template(
                'patient_list.j2',
                patients=patients)

        assign_response = loads(request.values['assign_response'])

        return render_template(
            'patient_list.j2',
            patients=patients,
            has_response=True,
            assign_response=assign_response)

    departments = HospitalController().get_department_list()
    patient = request.values.get('patient_id')
    patient = PatientController().find_patient(patient)

    return render_template(
        'patient_list.j2',
        has_departments=True,
        departments=departments,
        detailed_patient_data=patient,
        patients=patients)


@patients_bp.route('/assign', methods=['POST'])
@requires_login
@requires_permission
def assign_to_department():
    patients_view.info(msg=f'Recieved request to assign patient into department')

    to_assign = request.values.get('patient_id')
    where_to_assign = request.values.get('department_id')

    assign_response = PatientController().assign_patient(to_assign, where_to_assign)
    patients_view.debug(msg=f'Redirects back to patient list')
    return redirect(url_for('.list_patients', assign_response=dumps(assign_response)))


@patients_bp.route('/department', methods=['GET', 'POST'])
@requires_login
@requires_permission
def department_report():
    patients_view.info(msg=f'Renders department report')
    departments = HospitalController().get_department_list()
    
    if request.method == 'GET':
        # render as default
        return render_template('hospital_department.j2', departments=departments)

    department_data = request.values.get('selected_department')
    try:
        # try to decode option from the request
        # redirect to 404 handler if something goes wrong
        department_data = loads(department_data)
        d_id = department_data['id']
        d_title = department_data['title']

    except (JSONDecodeError, KeyError):
        patients_view.error(msg=f'Failed to collect request data\
            expected title and id, found: {department_data}')
        return redirect(url_for('page_not_found_redirect'))

    report = HospitalController().make_department_report(d_id, d_title)
    return render_template('hospital_department.j2', departments=departments, report=report)

view/patients/templates/hospital_department.j2
{% extends 'patient_menu.j2' %}

{% block title %}
Отчет об отделениях
{% endblock title %}

{% block content %}
<div class="container">
    <h1>Отделения</h1>
    {% if departments %}
    <div class="row">
        <div class="col-md-4">
            <form action="" method="post" class="form-horizontal">
                <table class="table table-borderless">
                    <tr>
                        <td>
                            <div class="form-group">                                
                                <select class="form-control form-select" name="selected_department" style="text-align: center;">
                                {% for department in departments %}
                                {% if report and department['title'] == report['title']%}
                                <option value='{"title":"{{ department['title'] }}", "id":"{{ department['id'] }}"}' 
                                    class="form-control" selected="selected">{{ department['title'] }}</option>
                                {% else %}
                                <option value='{"title":"{{ department['title'] }}", "id":"{{ department['id'] }}"}'
                                    class="form-control">{{ department['title'] }}</option>
                                {% endif %}
                                {% endfor %}
                                </select>
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                <input type="submit" class="form-control"  value="Выбрать" style="background-color: gainsboro;">
                            </div>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
        <div class="col-md-8">
        {% if report %}
            <h3>{{ report['title'] }}. Заведующий отделением: {{ report['head'] }}</h3>
        {% else %}
            <p>Чтобы получить информацию о заведующем отделением и палатах,
                пожалуйста, выберите отделение в выпадающем списке.</p>
        {% endif %}
        </div>
    </div>
    {% else %}
        <div class="alert alert-danger">
            <strong>Произошла ошибка на сервере!</strong><p>Перезагрузите страницу или возвращайтесь позже...</p>
        </div>
    {% endif %}
    {% if report %}
        <div class="row">
            <div class="col-md-6">
                <table class="table table-striped">
                    <thead>
                        <tr style="font-weight: bold;">
                            <td>&#8470;</td>
                            <td>Тип палаты</td>
                            <td>Общее число мест</td>
                            <td>Занято мест</td>
                        </tr>
                    </thead>
                    <tbody>
                    {% for chamber in report['chambers'] %}
                        <tr>
                            <td>{{ chamber['num'] }}</td>
                            <td>{{ chamber['class'] }}</td>
                            <td>{{ chamber['capacity'] }}</td>
                            <td>{{ chamber['occupied'] }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-md-6">
                <table class="table table-striped">
                    <thead>
                        <tr style="font-weight: bold;">
                            <td>&#8470;</td>
                            <td>ФИО врача</td>
                            <td>Прикреплено пациентов</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for doctor in report['doctors'] %}
                        <tr>
                            <td>{{ doctor['num']}}</td>
                            <td>{{ doctor['name']}}</td>
                            <td>{{ doctor['assigned']}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </teble>
            </div>
        </div>
    {% endif %}
</div>
{% endblock content %}

view/patients/templates/patient_create.j2
{% extends 'patient_menu.j2' %}

{%block content%}

<div class="container" id="body">
    <div class="row" style="margin-top: 20px;">
        <div>
            <h1>Внести пациента в систему</h1>
            <p>Для того, чтобы создать новую запись для пациента, пожалуйста, заполните поля ниже. <br>
                Дата и место рождения пациента, а также его ФИО - это обязательные поля.
                Данные паспорта и симптомы (начальный диагноз) являются опциональными полями.</p>
        </div>
        <form class="form" action="" method="post">
            <div class="form-group">
                <table class="table table-borderless">
                    <tr>
                        <td>
                            <input class="form-control" type="text" name="initial_diagnosis" id="initial_diagnosis" placeholder="Симптомы, диагноз">
                        </td>
                    </tr>
                </table>
                <table class="table table-borderless">
                    <tr>
                        <td>
                            <input type="date" class="form-control col-sm-10" name="date_birth" required>
                        </td>
                        <td>
                            <input type="text" class="form-control col-sm-10" name="city" id="city" placeholder="Город" required>
                        </td>
                        <td>                                
                            <input type="password" name="passport" id="passport" class="form-control" placeholder="Паспорт: XX-XX-XXXX">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="text" class="form-control col-sm-6" name="first_name" id="first_name" placeholder="Имя" required>
                        </td>
                        <td>
                            <input type="text" class="form-control col-sm-6" name="second_name" id="second_name" placeholder="Фамилия" required>
                        </td>
                        <td>                                    
                            <input type="submit" class="form-control" id="submit" value="Добавить пациента" style="background-color: gainsboro;">
                        </td>
                    </tr>
                </table>
            </div>
        </form>
        {% if status %}
        <div class="row">
            {% if success %}
            <div class="alert alert-success">
                <strong>Пациент был успешно добавлен в систему!</strong>
            </div>
            {% else %}
            <div class="alert alert-danger">
                <strong>Во время добавления произошла ошибка, проверьте правильность введенных данных</strong>
            </div>
            {% endif %}
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}

view/patients/templates/patient_discharge.j2
{% extends 'patient_menu.j2' %}

{% block title %}
Выписать пациентов
{% endblock %}

{%block content%}

<div class="container" id="body">
    <div class="row" style="margin-top: 20px;">
        <div>
            <h1>Произвести выписку из госпиталя</h1>
            <p>Для того, чтобы выписать пациента из госпиталя, нажмите на соответствующую кнопку. 
                В качестве даты выписки будет выбрано сегодня.</p>
        </div>
    </div>
    <div class="row">
        {% if with_diag %}
        <table class="table">
            <thead>
                <tr>
                    <th>&#8470;</th>
                    <th>ФИО</th>
                    <th>Дата рождения</th>
                    <th>Город</th>
                    <th>Дата обращения</th>
                    <th>Симптомы, жалобы</th>
                    <th>Окончательный диагноз</th>
                    <th>ФИО лечащего врача</th>
                    <th>Палата</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for patient in with_diag %}
                <tr>
                    <td>{{ patient['num'] }}</td>
                    <td>{{ patient['name'] }}</td>
                    <td>{{ patient['birth_date'] }}</td>
                    <td>{{ patient['city'] }}</td>
                    <td>{{ patient['income_date'] }}</td>
                    <td>{{ patient['income_diag'] }}</td>
                    <td>{{ patient['outcome_diag'] }}</td>
                    <td>{{ patient['attending_doctor'] }}</td>
                    <td>{{ patient['chamber'] }}</td>
                    <td>
                        <form action="" class="form" method="post">
                            <input type="hidden" name="to_remove_id" value="{{patient['id']}}">
                            <input type="hidden" name="attending_doctor" value="{{patient['id_doctor']}}">
                            <input type="hidden" name="occupied_chamber" value="{{patient['chamber']}}">
                            <input type="submit" value="Выписать" class="form-control" style="background-color: gainsboro;">
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <div class="alert alert-warning">
            <h2>В данный момент нет пациентов, готовых к выписке!</h2>
        </div>
        {% endif %}
    </div>
    {% if show_alert %}
    <div class="row">
        <div class="alert alert-success">
            <strong>Пациент был успешно выписан!</strong>
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}

view/patients/templates/patient_list.html
{% extends 'app_layout.html' %}

{%block title%}
Hospital
{%endblock%}

{%block styles%}
    {{ super() }}
    <link href="{{ url_for('patients_bp.static', filename='css/home.css') }}" rel="stylesheet">
    <link href="{{ url_for('patients_bp.static', filename='css/table.css') }}" rel="stylesheet">
{%endblock%}

{%block icon%}
<link rel="shortcut icon" type="image/png" href="{{ url_for('patients_bp.static', filename='img/icon.png') }}">
{%endblock%}

{%block body%}

<div class="container" id="body">
    <div class="row">
        <div class="col-md 12">
            {% if patients %}
            <h1>Patients</h1>
            <table class="table">
                <thead>
                    <tr>
                        <th>&#8470;</th>
                        <th>Name</th>
                        <th>Birth Date</th>
                        <th>City</th>
                        <th>Income Date</th>
                        <th>Outcome Date</th>
                        <th>Initial diag</th>
                        <th>Outcome diag</th>
                        <th>Chamber &#8470;</th>
                        <th>Attending doctor</th>
                        <th>Edit</th>
                    </tr>
                </thead>
                <tbody>
                {% for patient in patients %}
                {% if patient['active'] %}
                    <tr class="active">
                        <td>{{patient['num']}}</td>
                        <td>{{patient['name']}}</td>
                        <td>{{patient['birth_date']}}</td>
                        <td>{{patient['city']}}</td>
                        <td>{{patient['income_date']}}</td>
                        <td>{{patient['outcome_date']}}</td>
                        <td>{{patient['income_diag']}}</td>
                        <td>{{patient['outcome_diag']}}</td>
                        <td>{{patient['chamber']}}</td>
                        <td>{{patient['doctor']}}</td>
                        <td>
                            <form action="" method="post">
                                <input type="hidden" name="patient_id" value="{{patient['id']}}">
                                <input type="submit" value="Discharge">
                            </form>
                        </td>
                    </tr>
                {% else %}
                    <tr class="alert alert-warning">
                        <td>{{patient['num']}}</td>
                        <td>{{patient['name']}}</td>
                        <td>{{patient['birth_date']}}</td>
                        <td>{{patient['city']}}</td>
                        <td>{{patient['income_date']}}</td>
                        <td>{{patient['outcome_date']}}</td>
                        <td>{{patient['income_diag']}}</td>
                        <td>{{patient['outcome_diag']}}</td>
                        <td>{{patient['chamber']}}</td>
                        <td>{{patient['doctor']}}</td>
                        <td></td>
                    </tr>
                {% endif %}
                {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
    </div>
    <div class="row">
            {% if chambers_full %}
            <div class="alert alert-danger">
                <strong>Accomodation inavaliable:</strong>
                chambers are filled entirely!
            </div>
            {% else %}
            <div>
                <h1>Create new patient record:</h1>
            </div>
            <form class="form" action="{{ url_for('patients_bp.add_new_patient') }}" method="post">
                <div class="form-group">
                    <input type="hidden" class="form-control" name="chamber" value="{{ optimal_chamber }}">
                    <label style="font-weight: bold;" for="birthday" class="control-label col-sm-2">Date of birth:</label>
                    <input type="date" class="form-control col-sm-10" name="date_birth" id="birthday" required>
                    <label style="font-weight: bold;" for="city" class="control-label col-sm-2">City:</label>
                    <input type="text" class="form-control col-sm-10" name="city" id="city" placeholder="Enter city name here" required>
                </div>
                <div class="form-group">
                    <label for="passport" class="control-label col-sm-2">Passport</label>
                    <input type="text" name="passport" id="passport" class="form-control" placeholder="XX-XX-XXXX">
                </div>
                <div class="form-group">
                    <label style="font-weight: bold;" for="first_name" class="control-label col-sm-2">First name:</label>
                    <input type="text" class="form-control col-sm-6" name="first_name" id="first_name" placeholder="Write here" required>
                    <label style="font-weight: bold;" for="second_name" class="control-label col-sm-2">Second name:</label>
                    <input type="text" class="form-control col-sm-6" name="second_name" id="second_name" placeholder="Write here" required>
                </div>
                <div class="form-group">
                    <label style="font-weight: bold;" for="doctor" class="control-label col-sm-2">Assign to doctor:</label>
                    <select class="form-control" name="attending_doctor" id="doctor">
                    {% for doctor in doctors %}
                        <option value="{{ doctor['id'] }}">{{ doctor['name'] }}</option>
                    {% endfor %}
                    </select>
                    <label for="submit"></label>
                    <input type="submit" class="form-control" id="submit" placeholder="Add new patient">
                </div>
            </form>
            {% endif %}
    </div>
    <div class="row">
        <div class="col-md-6" style="text-align: center;">
            <a href="{{ url_for('hospital_bp.get_hospital_menu') }}">Go back</a>
        </div>
        <div class="col-md-6" style="text-align: center;">
            <a href="{{ url_for('welcome_page') }}">Go to the main menu</a>
        </div>
    </div>
</div>

{% endblock %}

view/patients/templates/patient_list.j2
{% extends 'patient_menu.j2' %}

{% block title %}
Распределить пациентов
{% endblock %}

{%block content%}

<div class="container" id="body">
    <div class="row">
        <div class="col-md 12">
            {% if patients %}
            <h1>Не распределенные пациенты</h1>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>&#8470;</th>
                        <th>ФИО</th>
                        <th>Дата рождения</th>
                        <th>Город</th>
                        <th>Дата обращения</th>
                        <th>Симптомы, жалобы</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                {% for patient in patients %}
                    <tr>
                        <td>{{patient['num']}}</td>
                        <td>{{patient['name']}}</td>
                        <td>{{patient['birth_date']}}</td>
                        <td>{{patient['city']}}</td>
                        <td>{{patient['income_date']}}</td>
                        <td>{{patient['income_diag']}}</td>
                        <td>
                            <form class="form" action="" method="post">
                                <input type="hidden" name="patient_id" value="{{patient['id']}}">
                                <input class="form-control" type="submit" value="Выбрать отделение" style="background-color: gainsboro;">
                            </form>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
        {% if has_departments and detailed_patient_data %}
            <h1>Определить в отделение</h1>
            <table class="table table-borderless">
                <thead>
                    <th>ФИО</th>
                    <th>Дата рождения</th>
                    <th>Город</th>
                    <th>Симптомы, жалобы</th>
                    <th>Ожидает распределения</th>
                </thead>
                <tr>
                    <td>{{detailed_patient_data['name']}}</td>
                    <td>{{detailed_patient_data['birth_date']}}</td>
                    <td>{{detailed_patient_data['city']}}</td>
                    <td>{{detailed_patient_data['income_diag']}}</td>
                    <td>{{detailed_patient_data['awaiting']}}</td>
                </tr>
            </table>
            {% if departments %}
            <form method="post" action="{{ url_for('.assign_to_department')}}" class="form">
                <table style="width: 100%; align-items: center">
                    <tr>
                        <td>
                            <select class="form-control form-select" name="department_id" id="department">
                            {% for department in departments %}
                                <option value="{{ department['id'] }}">{{ department['title'] }}</option>
                            {% endfor %}
                            </select>
                        </td>
                        <td>
                            <input type="hidden" class="form-control" name="patient_id" value="{{ detailed_patient_data['id'] }}">
                            <input type="submit" class="form-control" id="submit" value="Определить" style="background-color: gainsboro;">
                        </td>
                    </tr>
                </table>
            </form>
            {% else %}
            <div class="alert alert-danger">
                <strong>Произошла ошибка во время получения данных об отделениях!</strong>
                <p>Попробуйте снова</p>
            </div>
            {% endif %}
            {% endif %}
            {% if assign_response %}
            <div class="alert alert-success">
                <strong>Назначен лечащий врач: {{ assign_response['attending_doctor'] }}. Палата &#8470; {{ assign_response['chamber'] }}</strong>
            </div>
            {% elif has_response %}
            <div class="alert alert-warning">
                <strong>Произошла ошибка во время прикрепления к отделению</strong>
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

view/patients/templates/patient_menu.j2
{% extends 'menu.j2' %}
{%block title%}
Пациенты
{%endblock%}

{%block styles%}
    {{ super() }}
    <link href="{{ url_for('.static', filename='css/home.css') }}" rel="stylesheet">
    <link href="{{ url_for('.static', filename='css/table.css') }}" rel="stylesheet">
{%endblock%}

{%block icon%}
<link rel="shortcut icon" type="image/png" href="{{ url_for('.static', filename='img/icon.png') }}">
{%endblock%}

{%block navbar %}
{{ navlink('.list_patients', 'Распределение пациентов') }}
{{ navlink('.add_new_patient', 'Внести пациентв') }}
{{ navlink('.list_dischargable', 'Выписка пациентов') }}
{{ navlink('.department_report', 'Отчет') }}
{%endblock%}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="alert alert-info" style="margin-top: 30%;">
                <h1>Раздел регистратуры</h1>
                <p>Выберите раздел для работы из меню выше</p>
                <p>
                    В данном разделе производятся основные действия по приемке
                    и распредению пациентов госпиталя. Изначально необходимо заполнить основные
                    данные о новом пациенте, такие как ФИО, дата рождения, симптомы.
                    Затем пациентов распределяют по отделениям. Необходимо выбрать отделение
                    на основании диагноза. Система подберет подходящих врача и палату самостоятельно.
                    <br>
                    Когда врач убедится в том, что пациент прошел курс лечения и может покинуть
                    госпиталь, он отметит его соответствующим образом. Готовых к выписке пациентов можно
                    найти в соответствующем разделе.
                    <br>
                    Если будут возникать вопросы о состоянии отделения,
                    данные по ним расположены в разделе меню выше.
                </p>
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{%endblock%}